lab3:
  stage: test
  image:
    name: python-tools
    entrypoint: [""]
  script:
    - python3-coverage run -m pytest --verbose
    - find src test -type f -name "*.py" | xargs -t python3-coverage report
    - find src test -type f -name "*.py" | xargs -t pep8 --ignore=E501
    - find src test -type f -name "*.py" | xargs -t pylint
