name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Setup python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Pip install
        run: |
          python3 -m pip install coverage pycodestyle pylint pytest

      - name: Test
        run: |
          coverage run -m pytest --verbose
          find . -type f -name "*.py" | xargs -t python3 -m coverage report
          find . -type f -name "*.py" | xargs -t python3 -m pycodestyle --ignore=E501
          find . -type f -name "*.py" | xargs -t python3 -m pylint

